spring.application.name=CoffeeStack

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeestack
spring.datasource.username=coffeestack_user
spring.datasource.password=coffeestack

# because we use flyway we set hibernate to just validate
spring.jpa.hibernate.ddl-auto=validate